//  DietPlanView.swift
//  food-app-swift
//
//  Created by Helen Tu on 4/8/26.
//
//  DietPlanView.swift — v3: Option A food cards + Option Y AI waveform
//  DietPlanView.swift — v4: scroll/paged toggle + share report
import SwiftUI

// MARK: - View Mode

enum ReportViewMode: String, CaseIterable {
    case scroll = "Scroll"
    case paged  = "Paged"
    var icon: String { self == .scroll ? "rectangle.arrowtriangle.2.outward" : "rectangle.on.rectangle" }
}

// MARK: - Share Sheet


func buildReportText(_ report: HealthReport) -> String {
    var lines = ["NutriCam Health Report",
                 "Health Score: \(report.healthScore)/100 — \(report.statusBadge)", "",
                 report.healthSummary, "",
                 "Daily Nutrition Goals",
                 "Calories: \(report.dailyCalories) kcal",
                 "Protein: \(report.proteinG)g  |  Carbs: \(report.carbsG)g  |  Fat: \(report.fatG)g",
                 "Fiber: \(report.fiberG)g  |  Sodium: \(report.sodiumMg)mg",
                 "Weekly total: \(report.weeklyCalories) kcal"]
    if !report.attentionItems.isEmpty {
        lines += ["", "Health Indicators"]
        lines += report.attentionItems.map { "• \($0.metric): \($0.currentValue) — \($0.advice)" }
    }
    if !report.recommendedFoods.isEmpty {
        lines += ["", "Recommended Foods"]
        lines += report.recommendedFoods.map { "• \($0.food): \($0.reason)" }
    }
    if !report.foodsToLimit.isEmpty {
        lines += ["", "Foods to Limit", report.foodsToLimit.joined(separator: ", ")]
    }
    lines += ["", "Tip: \(report.lifestyleTip)", "", "Generated by NutriCam AI"]
    return lines.joined(separator: "\n")
}

// MARK: - AI Waveform Strip

struct AIWaveformStrip: View {
    @EnvironmentObject var themeManager: ThemeManager
    let report: HealthReport
    var hasBP: Bool      { report.attentionItems.contains { $0.metric.lowercased().contains("blood pressure") || $0.metric.lowercased().contains("bp") } }
    var hasGlucose: Bool { report.attentionItems.contains { $0.metric.lowercased().contains("sugar") || $0.metric.lowercased().contains("glucose") } }
    var bmiDetail: String {
        report.attentionItems.first { $0.metric.lowercased().contains("bmi") }.map { "\($0.currentValue) · \($0.status.capitalized)" } ?? "Analysed"
    }
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 10) {
                HStack(alignment: .bottom, spacing: 2) {
                    ForEach(Array([6,14,18,9,12,5,16].enumerated()), id: \.0) { i, base in
                        WaveBar(baseH: CGFloat(base), delay: Double(i) * 0.12)
                    }
                }.frame(height: 24)
                Text("NutriCam AI scanned your profile")
                    .font(.system(size: 12, weight: .bold))
                    .foregroundColor(Color(red:0.76,green:0.32,blue:0.04))
            }
            VStack(spacing: 8) {
                AICheckItem(status: .done,  label: "Body composition", detail: bmiDetail)
                AICheckItem(status: hasBP ? .done : .warn, label: "Heart health", detail: hasBP ? "BP normal" : "No BP data — add for accuracy")
                AICheckItem(status: hasGlucose ? .done : .warn, label: "Glucose & lipids", detail: hasGlucose ? "Values detected" : "No data — add for accuracy")
                AICheckItem(status: .done, label: "Nutrition targets", detail: "\(report.dailyCalories) kcal/day set")
            }
        }
        .padding(14)
        .background(Color.orange.opacity(0.04)).cornerRadius(16)
        .overlay(RoundedRectangle(cornerRadius: 16).stroke(Color.orange.opacity(0.15), lineWidth: 1))
    }
}

struct WaveBar: View {
    let baseH: CGFloat; let delay: Double
    @State private var phase = false
    var body: some View {
        RoundedRectangle(cornerRadius: 2).fill(Color.orange)
            .frame(width: 3, height: phase ? max(4, baseH * 0.3) : baseH)
            .onAppear {
                DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
                    withAnimation(Animation.easeInOut(duration: 0.9).repeatForever(autoreverses: true)) { phase = true }
                }
            }
    }
}

enum AICheckStatus { case done, warn }
struct AICheckItem: View {
    @EnvironmentObject var themeManager: ThemeManager
    let status: AICheckStatus; let label: String; let detail: String
    var body: some View {
        HStack(spacing: 8) {
            ZStack {
                Circle().fill(status == .done ? Color.green.opacity(0.15) : Color.orange.opacity(0.15)).frame(width: 18, height: 18)
                Image(systemName: status == .done ? "checkmark" : "exclamationmark")
                    .font(.system(size: 8, weight: .bold)).foregroundColor(status == .done ? .green : .orange)
            }
            HStack(spacing: 3) {
                Text(label + " ·").font(.system(size: 12)).foregroundColor(themeManager.current.secondaryText)
                Text(detail).font(.system(size: 12, weight: .semibold))
                    .foregroundColor(status == .warn ? Color(red:0.57,green:0.25,blue:0.0) : themeManager.current.primaryText)
            }
            Spacer()
        }
    }
}

// MARK: - Food Card A

struct FoodCardA: View {
    @EnvironmentObject var themeManager: ThemeManager
    let food: RecommendedFood
    var topColors: (Color, Color) {
        let l = food.food.lowercased()
        if l.contains("salmon")||l.contains("fish")||l.contains("tuna")||l.contains("shrimp") { return (Color(red:0.86,green:0.92,blue:1.0),Color(red:0.75,green:0.86,blue:1.0)) }
        if l.contains("chicken")||l.contains("turkey")||l.contains("egg") { return (Color(red:1.0,green:0.95,blue:0.82),Color(red:1.0,green:0.90,blue:0.65)) }
        if l.contains("broccoli")||l.contains("spinach")||l.contains("kale")||l.contains("avocado") { return (Color(red:0.86,green:0.97,blue:0.88),Color(red:0.73,green:0.94,blue:0.77)) }
        if l.contains("beef")||l.contains("meat")||l.contains("lentil")||l.contains("bean") { return (Color(red:0.98,green:0.90,blue:0.88),Color(red:0.96,green:0.78,blue:0.73)) }
        if l.contains("berry")||l.contains("blueberry")||l.contains("grape") { return (Color(red:0.92,green:0.88,blue:1.0),Color(red:0.82,green:0.76,blue:0.98)) }
        if l.contains("oat")||l.contains("quinoa")||l.contains("rice")||l.contains("grain") { return (Color(red:1.0,green:0.96,blue:0.80),Color(red:0.99,green:0.90,blue:0.60)) }
        if l.contains("yogurt")||l.contains("milk")||l.contains("cheese") { return (Color(red:0.94,green:0.94,blue:0.97),Color(red:0.86,green:0.86,blue:0.94)) }
        return (Color(red:0.85,green:0.96,blue:0.94),Color(red:0.70,green:0.92,blue:0.88))
    }
    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            ZStack {
                LinearGradient(colors:[topColors.0,topColors.1],startPoint:.topLeading,endPoint:.bottomTrailing)
                Text(foodEmoji(food.food)).font(.system(size: 44))
            }.frame(height: 76)
            VStack(alignment: .leading, spacing: 0) {
                Text(food.food).font(.system(size:14,weight:.bold)).foregroundColor(themeManager.current.primaryText).lineLimit(1).padding(.bottom,3)
                Text(food.reason).font(.system(size:11)).foregroundColor(themeManager.current.secondaryText).lineLimit(2).fixedSize(horizontal:false,vertical:true).padding(.bottom,10)
                Rectangle().fill(themeManager.current.cardBorder).frame(height:0.5).padding(.bottom,8)
                Text("TRY THESE").font(.system(size:9,weight:.bold)).foregroundColor(themeManager.current.secondaryText).tracking(0.5).padding(.bottom,5)
                ForEach(food.dishes.prefix(2),id:\.self) { dish in
                    HStack(spacing:5) {
                        Circle().fill(Color.green.opacity(0.6)).frame(width:4,height:4)
                        Text(dish).font(.system(size:11)).foregroundColor(themeManager.current.primaryText).lineLimit(1)
                    }.padding(.bottom,3)
                }
            }.padding(10).padding(.bottom,2)
        }
        .frame(width:152)
        .background(themeManager.current.cardBackground).cornerRadius(16)
        .overlay(RoundedRectangle(cornerRadius:16).stroke(themeManager.current.cardBorder,lineWidth:0.5))
        .clipped()
    }
    func foodEmoji(_ f: String) -> String {
        let l=f.lowercased()
        if l.contains("salmon")||l.contains("fish")||l.contains("tuna"){return"🐟"}
        if l.contains("chicken")||l.contains("turkey"){return"🍗"}
        if l.contains("beef")||l.contains("meat"){return"🥩"}
        if l.contains("egg"){return"🥚"};if l.contains("tofu")||l.contains("soy"){return"🫘"}
        if l.contains("broccoli"){return"🥦"};if l.contains("spinach")||l.contains("kale"){return"🥬"}
        if l.contains("avocado"){return"🥑"};if l.contains("quinoa")||l.contains("oat"){return"🌾"}
        if l.contains("blueberry")||l.contains("berry"){return"🫐"};if l.contains("apple"){return"🍎"}
        if l.contains("banana"){return"🍌"};if l.contains("almond")||l.contains("nut"){return"🥜"}
        if l.contains("yogurt")||l.contains("milk"){return"🥛"};if l.contains("lentil")||l.contains("bean"){return"🫘"}
        if l.contains("sweet potato")||l.contains("potato"){return"🍠"};if l.contains("rice"){return"🍚"}
        if l.contains("olive"){return"🫒"};if l.contains("shrimp")||l.contains("prawn"){return"🍤"}
        return"🥗"
    }
}

// MARK: - Main DietPlanView

struct DietPlanView: View {
    @EnvironmentObject var themeManager: ThemeManager
    @ObservedObject var session = SessionManager.shared
    @State private var healthProfile: HealthProfile?
    @State private var healthReport: HealthReport?
    @State private var isLoading = false
    @State private var isGenerating = false
    @State private var errorMsg = ""
    @State private var showError = false
    @State private var showProfileSetup = false
    @State private var showRefreshPrompt = false
    @State private var viewMode: ReportViewMode = .scroll
    @State private var pagedIndex: Int = 0
    @State private var showShareSheet = false
    @State private var shareItems: [Any] = []

    var currentUserId: String { session.userID.isEmpty ? UserDefaults.standard.string(forKey:"user_id") ?? "" : session.userID }

    var body: some View {
        NavigationStack {
            ZStack {
                themeManager.current.background.ignoresSafeArea()
                if isLoading { loadingView }
                else if isGenerating { generatingView }
                else if healthProfile == nil { noProfileView }
                else if let report = healthReport {
                    if viewMode == .scroll { scrollReport(report: report) }
                    else { pagedReport(report: report) }
                }
                else { generatePromptView }
            }
            .preferredColorScheme(themeManager.current.colorScheme)
            .navigationBarHidden(true)
            .onAppear { loadData() }
            .alert("Error", isPresented: $showError) { Button("OK", role: .cancel) {} } message: { Text(errorMsg) }
            .sheet(isPresented: $showProfileSetup) {
                HealthProfileView { profile in
                    self.healthProfile = profile
                    HealthAPIManager.shared.saveHealthProfile(profile) { _,_ in }
                    generateReport(force: true)
                }.environmentObject(themeManager)
            }
            .sheet(isPresented: $showShareSheet) { ShareSheet(items: shareItems) }
            .alert("Update Your Health Plan?", isPresented: $showRefreshPrompt) {
                Button("Yes, Regenerate") { generateReport(force: true) }
                Button("Keep Current Plan", role: .cancel) {}
            } message: { Text("It's been over 7 days since your last report. Refresh with your latest profile?") }
        }
    }

    // MARK: - Data

    func loadData() {
        guard healthReport == nil, !isLoading, !isGenerating else { return }
        isLoading = true
        HealthAPIManager.shared.fetchHealthProfile(userId: currentUserId) { profile in
            self.healthProfile = profile
            guard profile != nil else { self.isLoading = false; return }
            HealthAPIManager.shared.fetchHealthReport { report in
                self.isLoading = false
                if let r = report { self.healthReport = r; self.checkReportAge(report: r) }
                else { self.generateReport(force: false) }
            }
        }
    }

    func checkReportAge(report: HealthReport) {
        guard let str = report.createdAt else { return }
        let f1 = ISO8601DateFormatter(); f1.formatOptions = [.withInternetDateTime,.withFractionalSeconds]
        let f2 = ISO8601DateFormatter(); f2.formatOptions = [.withInternetDateTime]
        guard let date = f1.date(from: str) ?? f2.date(from: str) else { return }
        let days = Calendar.current.dateComponents([.day], from: date, to: Date()).day ?? 0
        if days >= 7 { DispatchQueue.main.asyncAfter(deadline: .now()+0.5) { self.showRefreshPrompt = true } }
    }

    func generateReport(force: Bool) {
        isGenerating = true
        HealthAPIManager.shared.generateHealthReport(goals: [], force: force) { report, err in
            self.isGenerating = false
            if let r = report { self.healthReport = r }
            else { self.errorMsg = err ?? "Failed to generate report"; self.showError = true }
        }
    }

    // MARK: - Top Bar

    func topBar(report: HealthReport) -> some View {
        HStack(alignment: .top) {
            VStack(alignment: .leading, spacing: 3) {
                Text("Health Report").font(.system(size: 26, weight: .black, design: .rounded)).foregroundColor(themeManager.current.primaryText)
                if let date = report.createdAt {
                    Text("Updated \(formatDate(date))").font(.system(size: 12)).foregroundColor(themeManager.current.secondaryText)
                }
            }
            Spacer()
            HStack(spacing: 10) {
                Button(action: { showProfileSetup = true }) {
                    HStack(spacing: 5) {
                        Image(systemName: "pencil").font(.system(size: 11, weight: .semibold))
                        Text("Edit").font(.system(size: 12, weight: .semibold))
                    }
                    .foregroundColor(themeManager.current == .dark ? .black : .white)
                    .padding(.horizontal, 10).padding(.vertical, 7)
                    .background(themeManager.current == .dark ? Color.white : Color.black).cornerRadius(20)
                }
                Menu {
                    Section("View") {
                        ForEach(ReportViewMode.allCases, id: \.self) { mode in
                            Button(action: { withAnimation(.spring(response:0.35,dampingFraction:0.8)) { viewMode = mode; pagedIndex = 0 } }) {
                                Label(viewMode == mode ? "\(mode.rawValue) ✓" : mode.rawValue, systemImage: mode.icon)
                            }
                        }
                    }
                    Divider()
                    Button(action: { shareItems = [buildReportText(report)]; showShareSheet = true }) {
                        Label("Share Report", systemImage: "square.and.arrow.up")
                    }
                    Button(action: { UIPasteboard.general.string = buildReportText(report) }) {
                        Label("Copy as Text", systemImage: "doc.on.doc")
                    }
                    Divider()
                    Button(action: { generateReport(force: true) }) {
                        Label("Regenerate Report", systemImage: "arrow.clockwise")
                    }
                } label: {
                    Image(systemName: "ellipsis.circle").font(.system(size: 20, weight: .medium))
                        .foregroundColor(themeManager.current.primaryText)
                        .frame(width: 36, height: 36).background(themeManager.current.inputBackground).cornerRadius(10)
                }
            }
        }
        .padding(.horizontal, 20).padding(.top, 20).padding(.bottom, 16)
    }

    // MARK: - Scroll Mode

    func scrollReport(report: HealthReport) -> some View {
        ScrollView(showsIndicators: false) {
            VStack(spacing: 0) {
                topBar(report: report)
                AIWaveformStrip(report: report).environmentObject(themeManager).padding(.horizontal,20).padding(.bottom,16)
                scoreHeroCard(report: report).padding(.horizontal,20).padding(.bottom,16)
                profileCompletenessCard(report: report).padding(.horizontal,20).padding(.bottom,16)
                nutritionGoalsCard(report: report).padding(.horizontal,20).padding(.bottom,16)
                if !report.attentionItems.isEmpty { healthIndicatorsSection(items: report.attentionItems).padding(.horizontal,20).padding(.bottom,16) }
                if !report.recommendedFoods.isEmpty { recommendedFoodsSection(foods: report.recommendedFoods).padding(.bottom,16) }
                if !report.foodsToLimit.isEmpty { foodsToLimitCard(foods: report.foodsToLimit).padding(.horizontal,20).padding(.bottom,16) }
                lifestyleTipCard(tip: report.lifestyleTip).padding(.horizontal,20).padding(.bottom,100)
            }
        }
    }

    // MARK: - Paged Mode

    func pagedReport(report: HealthReport) -> some View {
        var pages: [(String, AnyView)] = [
            ("Overview",        AnyView(VStack(spacing:16){ AIWaveformStrip(report:report).environmentObject(themeManager); scoreHeroCard(report:report); profileCompletenessCard(report:report) }.padding(.horizontal,20))),
            ("Nutrition Goals", AnyView(nutritionGoalsCard(report:report).padding(.horizontal,20))),
        ]
        if !report.attentionItems.isEmpty { pages.append(("Health Indicators", AnyView(healthIndicatorsSection(items:report.attentionItems).padding(.horizontal,20)))) }
        if !report.recommendedFoods.isEmpty { pages.append(("Recommended Foods", AnyView(recommendedFoodsSection(foods:report.recommendedFoods)))) }
        if !report.foodsToLimit.isEmpty || !report.lifestyleTip.isEmpty {
            pages.append(("Foods & Tip", AnyView(VStack(spacing:16){ if !report.foodsToLimit.isEmpty { foodsToLimitCard(foods:report.foodsToLimit).padding(.horizontal,20) }; lifestyleTipCard(tip:report.lifestyleTip).padding(.horizontal,20) })))
        }

        return VStack(spacing: 0) {
            topBar(report: report)
            // Dots + page counter
            HStack(spacing: 6) {
                ForEach(0..<pages.count, id: \.self) { i in
                    Capsule()
                        .fill(i == pagedIndex ? (themeManager.current == .dark ? Color.white : Color.black) : themeManager.current.cardBorder)
                        .frame(width: i == pagedIndex ? 20 : 6, height: 6)
                        .animation(.spring(response:0.3,dampingFraction:0.7), value: pagedIndex)
                }
                Spacer()
                Text("\(pagedIndex+1) / \(pages.count)").font(.system(size:12)).foregroundColor(themeManager.current.secondaryText)
            }
            .padding(.horizontal,20).padding(.bottom,12)

            TabView(selection: $pagedIndex) {
                ForEach(Array(pages.enumerated()), id: \.0) { idx, page in
                    ScrollView(showsIndicators: false) {
                        VStack(alignment: .leading, spacing: 0) {
                            Text(page.0).font(.system(size:13,weight:.semibold)).foregroundColor(themeManager.current.secondaryText)
                                .textCase(.uppercase).tracking(0.5).padding(.horizontal,20).padding(.bottom,14)
                            page.1
                            Spacer(minLength: 80)
                        }.padding(.top,4)
                    }.tag(idx)
                }
            }
            .tabViewStyle(.page(indexDisplayMode: .never))
        }
    }

    // MARK: - Cards

    func scoreHeroCard(report: HealthReport) -> some View {
        let color = scoreColor(report.healthScore)
        return HStack(spacing:20) {
            ZStack {
                Circle().stroke(color.opacity(0.12),lineWidth:12).frame(width:110,height:110)
                Circle().trim(from:0,to:CGFloat(report.healthScore)/100.0)
                    .stroke(color,style:StrokeStyle(lineWidth:12,lineCap:.round))
                    .frame(width:110,height:110).rotationEffect(.degrees(-90))
                    .animation(.easeOut(duration:1.2),value:report.healthScore)
                VStack(spacing:1) {
                    Text("\(report.healthScore)").font(.system(size:32,weight:.black,design:.rounded)).foregroundColor(themeManager.current.primaryText)
                    Text("/ 100").font(.system(size:11,weight:.medium)).foregroundColor(themeManager.current.secondaryText)
                }
            }
            VStack(alignment:.leading,spacing:10) {
                Text(report.statusBadge).font(.system(size:12,weight:.bold)).foregroundColor(color)
                    .padding(.horizontal,10).padding(.vertical,4).background(color.opacity(0.10)).cornerRadius(20)
                    .overlay(RoundedRectangle(cornerRadius:20).stroke(color.opacity(0.25),lineWidth:1))
                Text(report.healthSummary).font(.system(size:13)).lineSpacing(3).foregroundColor(themeManager.current.secondaryText).fixedSize(horizontal:false,vertical:true)
            }.frame(maxWidth:.infinity,alignment:.leading)
        }
        .padding(20).background(themeManager.current.cardBackground).cornerRadius(20)
        .overlay(RoundedRectangle(cornerRadius:20).stroke(color.opacity(0.15),lineWidth:1.5))
    }

    func scoreColor(_ s: Int) -> Color { s>=80 ? .green : s>=60 ? .orange : .red }

    func profileCompletenessCard(report: HealthReport) -> some View {
        let filled = min(report.attentionItems.filter { i in ["blood pressure","bp","sugar","glucose","cholesterol","triglycerides"].contains{i.metric.lowercased().contains($0)} }.count,4)
        let pct = Double(filled)/4.0; let done = filled==4
        return Button(action:{showProfileSetup=true}) {
            HStack(spacing:14) {
                ZStack {
                    Circle().stroke(themeManager.current.cardBorder,lineWidth:5).frame(width:44,height:44)
                    Circle().trim(from:0,to:pct).stroke(done ? Color.green : Color.orange,style:StrokeStyle(lineWidth:5,lineCap:.round))
                        .frame(width:44,height:44).rotationEffect(.degrees(-90))
                    Text("\(filled)/4").font(.system(size:11,weight:.bold,design:.rounded)).foregroundColor(themeManager.current.primaryText)
                }
                VStack(alignment:.leading,spacing:3) {
                    Text(done ? "Profile complete" : "Add more data for a better report").font(.system(size:14,weight:.semibold)).foregroundColor(themeManager.current.primaryText)
                    Text(done ? "All clinical markers filled — fully personalised" : "Blood pressure, glucose, cholesterol & triglycerides improve accuracy")
                        .font(.system(size:12)).foregroundColor(themeManager.current.secondaryText).fixedSize(horizontal:false,vertical:true)
                }
                Spacer()
                if !done { Image(systemName:"chevron.right").font(.system(size:12)).foregroundColor(themeManager.current.secondaryText.opacity(0.5)) }
            }
            .padding(14).background(done ? Color.green.opacity(0.04) : Color.orange.opacity(0.04)).cornerRadius(16)
            .overlay(RoundedRectangle(cornerRadius:16).stroke(done ? Color.green.opacity(0.15) : Color.orange.opacity(0.20),lineWidth:1))
        }.buttonStyle(.plain)
    }

    func nutritionGoalsCard(report: HealthReport) -> some View {
        let total = Double(report.proteinG*4 + report.carbsG*4 + report.fatG*9)
        let protPct = total>0 ? Double(report.proteinG*4)/total : 0
        let carbPct = total>0 ? Double(report.carbsG*4)/total : 0
        let fatPct  = total>0 ? Double(report.fatG*9)/total : 0
        return VStack(alignment:.leading,spacing:16) {
            HStack(alignment:.lastTextBaseline) {
                Text("Daily Nutrition").font(.system(size:15,weight:.bold)).foregroundColor(themeManager.current.primaryText)
                Spacer()
                VStack(alignment:.trailing,spacing:1) {
                    Text("\(report.dailyCalories)").font(.system(size:20,weight:.black,design:.rounded)).foregroundColor(themeManager.current.primaryText)
                    Text("kcal / day").font(.system(size:11)).foregroundColor(themeManager.current.secondaryText)
                }
            }
            HStack(spacing:18) {
                ZStack {
                    Circle().stroke(themeManager.current.cardBorder,lineWidth:14).frame(width:100,height:100)
                    Circle().trim(from:0,to:CGFloat(protPct)).stroke(Color(red:0.93,green:0.36,blue:0.36),style:StrokeStyle(lineWidth:14,lineCap:.butt)).frame(width:100,height:100).rotationEffect(.degrees(-90))
                    Circle().trim(from:CGFloat(protPct),to:CGFloat(protPct+carbPct)).stroke(Color(red:0.95,green:0.61,blue:0.20),style:StrokeStyle(lineWidth:14,lineCap:.butt)).frame(width:100,height:100).rotationEffect(.degrees(-90))
                    Circle().trim(from:CGFloat(protPct+carbPct),to:CGFloat(protPct+carbPct+fatPct)).stroke(Color(red:0.35,green:0.62,blue:0.93),style:StrokeStyle(lineWidth:14,lineCap:.butt)).frame(width:100,height:100).rotationEffect(.degrees(-90))
                    VStack(spacing:1) {
                        Text("\(report.dailyCalories)").font(.system(size:14,weight:.black,design:.rounded)).foregroundColor(themeManager.current.primaryText).minimumScaleFactor(0.6)
                        Text("kcal").font(.system(size:9,weight:.semibold)).foregroundColor(themeManager.current.secondaryText)
                    }
                }
                VStack(alignment:.leading,spacing:7) {
                    legendRow("Protein",value:"\(report.proteinG)g",pct:Int(protPct*100),color:Color(red:0.93,green:0.36,blue:0.36))
                    legendRow("Carbs",  value:"\(report.carbsG)g",  pct:Int(carbPct*100),color:Color(red:0.95,green:0.61,blue:0.20))
                    legendRow("Fat",    value:"\(report.fatG)g",    pct:Int(fatPct*100), color:Color(red:0.35,green:0.62,blue:0.93))
                    Divider().background(themeManager.current.cardBorder)
                    legendRow("Fiber", value:"\(report.fiberG)g",   pct:nil,color:.green, check:true)
                    legendRow("Sodium",value:"\(report.sodiumMg)mg",pct:nil,color:.purple,check:true)
                }
            }
        }
        .padding(18).background(themeManager.current.cardBackground).cornerRadius(18)
        .overlay(RoundedRectangle(cornerRadius:18).stroke(themeManager.current.cardBorder,lineWidth:1))
    }

    func legendRow(_ name:String,value:String,pct:Int?,color:Color,check:Bool=false) -> some View {
        HStack(spacing:6) {
            Circle().fill(color).frame(width:8,height:8)
            Text(name).font(.system(size:12)).foregroundColor(themeManager.current.secondaryText)
            Spacer()
            Text(value).font(.system(size:12,weight:.bold)).foregroundColor(themeManager.current.primaryText)
            if let p=pct { Text("\(p)%").font(.system(size:11)).foregroundColor(themeManager.current.secondaryText).frame(width:30,alignment:.trailing) }
            else if check { Image(systemName:"checkmark").font(.system(size:9,weight:.bold)).foregroundColor(.green).frame(width:30,alignment:.trailing) }
        }
    }

    func healthIndicatorsSection(items:[AttentionItem]) -> some View {
        VStack(alignment:.leading,spacing:12) {
            ForEach(items) { item in
                let color:Color = item.status=="normal" ? .green : item.status=="borderline" ? .orange : .red
                HStack(alignment:.top,spacing:12) {
                    Image(systemName:item.status=="normal" ? "checkmark.circle.fill" : item.status=="borderline" ? "exclamationmark.triangle.fill" : "xmark.circle.fill")
                        .font(.system(size:16)).foregroundColor(color).frame(width:28,height:28).background(color.opacity(0.08)).cornerRadius(8)
                    VStack(alignment:.leading,spacing:5) {
                        HStack(alignment:.firstTextBaseline) {
                            Text(item.metric).font(.system(size:14,weight:.semibold)).foregroundColor(themeManager.current.primaryText)
                            Spacer()
                            Text(item.currentValue).font(.system(size:13,weight:.bold,design:.rounded)).foregroundColor(color)
                        }
                        Text(item.advice).font(.system(size:12)).lineSpacing(2).foregroundColor(themeManager.current.secondaryText).fixedSize(horizontal:false,vertical:true)
                    }
                }
                .padding(14).background(color.opacity(0.04)).cornerRadius(14)
                .overlay(RoundedRectangle(cornerRadius:14).stroke(color.opacity(0.15),lineWidth:1))
            }
        }
    }

    func recommendedFoodsSection(foods:[RecommendedFood]) -> some View {
        VStack(alignment:.leading,spacing:12) {
            HStack {
                VStack(alignment:.leading,spacing:2) {
                    Text("Recommended Foods").font(.system(size:15,weight:.bold)).foregroundColor(themeManager.current.primaryText)
                    Text("Personalised for your health profile").font(.system(size:12)).foregroundColor(themeManager.current.secondaryText)
                }
                Spacer()
                Text("\(foods.count) foods").font(.system(size:12,weight:.medium)).foregroundColor(themeManager.current.secondaryText)
                    .padding(.horizontal,10).padding(.vertical,4).background(themeManager.current.inputBackground).cornerRadius(12)
            }.padding(.horizontal,20)
            ScrollView(.horizontal,showsIndicators:false) {
                HStack(spacing:10) {
                    ForEach(Array(foods.enumerated()),id:\.offset) { _,food in FoodCardA(food:food).environmentObject(themeManager) }
                }.padding(.horizontal,20).padding(.vertical,4)
            }
        }
    }

    func foodsToLimitCard(foods:[String]) -> some View {
        VStack(alignment:.leading,spacing:12) {
            HStack(spacing:7) {
                Image(systemName:"hand.raised.fill").font(.system(size:13)).foregroundColor(.orange)
                Text("Foods to Limit").font(.system(size:15,weight:.bold)).foregroundColor(themeManager.current.primaryText)
            }
            Text("Reducing these supports your health goals").font(.system(size:12)).foregroundColor(themeManager.current.secondaryText)
            LazyVGrid(columns:[GridItem(.flexible()),GridItem(.flexible())],spacing:8) {
                ForEach(foods,id:\.self) { food in
                    HStack(spacing:6) {
                        ZStack { Circle().fill(Color.orange.opacity(0.15)).frame(width:16,height:16); Rectangle().fill(Color.orange).frame(width:6,height:1.5).cornerRadius(1) }
                        Text(food.components(separatedBy:" (").first ?? food).font(.system(size:12,weight:.medium)).foregroundColor(Color(red:0.76,green:0.32,blue:0.04)).lineLimit(1)
                        Spacer(minLength:0)
                    }
                    .padding(.horizontal,10).padding(.vertical,7).background(Color.orange.opacity(0.07)).cornerRadius(20)
                    .overlay(RoundedRectangle(cornerRadius:20).stroke(Color.orange.opacity(0.18),lineWidth:1))
                }
            }
        }
        .padding(16).background(themeManager.current.cardBackground).cornerRadius(18)
        .overlay(RoundedRectangle(cornerRadius:18).stroke(Color.orange.opacity(0.15),lineWidth:1))
    }

    func lifestyleTipCard(tip:String) -> some View {
        HStack(alignment:.top,spacing:14) {
            ZStack {
                RoundedRectangle(cornerRadius:10).fill(Color(red:0.95,green:0.75,blue:0.20).opacity(0.15)).frame(width:40,height:40)
                Image(systemName:"lightbulb.fill").font(.system(size:18)).foregroundColor(Color(red:0.95,green:0.75,blue:0.20))
            }
            VStack(alignment:.leading,spacing:5) {
                Text("Daily Habit Tip").font(.system(size:11,weight:.bold)).foregroundColor(Color(red:0.75,green:0.55,blue:0.0)).textCase(.uppercase).tracking(0.4)
                Text(tip).font(.system(size:14)).lineSpacing(3).foregroundColor(themeManager.current.primaryText).fixedSize(horizontal:false,vertical:true)
            }
        }
        .padding(16).background(Color(red:0.95,green:0.75,blue:0.20).opacity(0.07)).cornerRadius(16)
        .overlay(RoundedRectangle(cornerRadius:16).stroke(Color(red:0.95,green:0.75,blue:0.20).opacity(0.18),lineWidth:1))
    }

    // MARK: - State Views

    var loadingView: some View {
        VStack(spacing:16) {
            ProgressView().progressViewStyle(CircularProgressViewStyle(tint:themeManager.current.primaryText)).scaleEffect(1.3)
            Text("Loading your health report…").font(.system(size:14)).foregroundColor(themeManager.current.secondaryText)
        }
    }

    var generatingView: some View {
        VStack(spacing:28) {
            Spacer()
            ZStack { Circle().stroke(themeManager.current.cardBorder,lineWidth:3).frame(width:80,height:80); Image(systemName:"waveform.path.ecg").font(.system(size:32)).foregroundColor(themeManager.current.secondaryText) }
            VStack(spacing:8) {
                Text("Generating your report…").font(.system(size:17,weight:.semibold)).foregroundColor(themeManager.current.primaryText)
                Text("This usually takes 10–20 seconds").font(.system(size:13)).foregroundColor(themeManager.current.secondaryText)
            }
            ProgressView().progressViewStyle(CircularProgressViewStyle(tint:themeManager.current.primaryText))
            Spacer()
        }
    }

    var noProfileView: some View {
        VStack(spacing:28) {
            Spacer()
            Image(systemName:"person.crop.circle.badge.plus").font(.system(size:60)).foregroundColor(themeManager.current.secondaryText.opacity(0.35))
            VStack(spacing:8) {
                Text("Set Up Your Health Profile").font(.system(size:20,weight:.bold)).foregroundColor(themeManager.current.primaryText)
                Text("We'll create a personalised nutrition plan based on your body metrics and health data.").font(.system(size:14)).foregroundColor(themeManager.current.secondaryText).multilineTextAlignment(.center).padding(.horizontal,40)
            }
            Button(action:{showProfileSetup=true}) { Text("Set Up Profile").font(.system(size:16,weight:.bold)).foregroundColor(themeManager.current == .dark ? .black : .white).frame(maxWidth:.infinity).padding(.vertical,16).background(themeManager.current == .dark ? Color.white : Color.black).cornerRadius(16) }.padding(.horizontal,40)
            Spacer()
        }
    }

    var generatePromptView: some View {
        VStack(spacing:28) {
            Spacer()
            Image(systemName:"waveform.path.ecg.rectangle").font(.system(size:56)).foregroundColor(themeManager.current.secondaryText.opacity(0.35))
            VStack(spacing:8) {
                Text("Generate Your Health Report").font(.system(size:20,weight:.bold)).foregroundColor(themeManager.current.primaryText)
                Text("Get AI-powered analysis with personalised food recommendations based on your profile.").font(.system(size:14)).foregroundColor(themeManager.current.secondaryText).multilineTextAlignment(.center).padding(.horizontal,40)
            }
            Button(action:{generateReport(force:true)}) { Text("Generate Report").font(.system(size:16,weight:.bold)).foregroundColor(themeManager.current == .dark ? .black : .white).frame(maxWidth:.infinity).padding(.vertical,16).background(themeManager.current == .dark ? Color.white : Color.black).cornerRadius(16) }.padding(.horizontal,40)
            Spacer()
        }
    }

    func formatDate(_ str:String) -> String {
        let f1=ISO8601DateFormatter(); f1.formatOptions=[.withInternetDateTime,.withFractionalSeconds]
        if let d=f1.date(from:str) { let out=DateFormatter(); out.dateFormat="MMM d, yyyy"; return out.string(from:d) }
        let f2=ISO8601DateFormatter(); f2.formatOptions=[.withInternetDateTime]
        if let d=f2.date(from:str) { let out=DateFormatter(); out.dateFormat="MMM d, yyyy"; return out.string(from:d) }
        return str
    }
}

// MARK: - FlowLayout
struct FlowLayout<Item:Hashable,Content:View>: View {
    let items:[Item]; let content:(Item)->Content
    @State private var totalHeight:CGFloat = .zero
    init(items:[Item],@ViewBuilder content:@escaping(Item)->Content){self.items=items;self.content=content}
    var body: some View { GeometryReader{geo in generateContent(in:geo)}.frame(height:totalHeight) }
    private func generateContent(in geo:GeometryProxy) -> some View {
        var width=CGFloat.zero; var height=CGFloat.zero
        return ZStack(alignment:.topLeading) {
            ForEach(items,id:\.self){item in
                content(item).padding(.trailing,8).padding(.bottom,8)
                    .alignmentGuide(.leading){d in if abs(width-d.width)>geo.size.width{width=0;height -= d.height};let r=width;if item==items.last{width=0}else{width -= d.width};return r}
                    .alignmentGuide(.top){_ in let r=height;if item==items.last{height=0};return r}
            }
        }
        .background(GeometryReader{g in Color.clear.preference(key:HeightPreferenceKey.self,value:g.size.height)})
        .onPreferenceChange(HeightPreferenceKey.self){totalHeight=$0}
    }
}
private struct HeightPreferenceKey:PreferenceKey {
    static var defaultValue:CGFloat = .zero
    static func reduce(value:inout CGFloat,nextValue:()->CGFloat){value=max(value,nextValue())}
}

// MARK: - HealthDashboardView & TodayView
struct HealthDashboardView: View {
    @EnvironmentObject var themeManager:ThemeManager
    let nutritionPlan:NutritionPlan; let healthProfile:HealthProfile
    @State private var selectedTab=0
    var body: some View {
        TabView(selection:$selectedTab) {
            DashboardView().environmentObject(themeManager).tabItem{Image(systemName:selectedTab==0 ? "house.fill":"house");Text("Today")}.tag(0)
            DietPlanView().environmentObject(themeManager).tabItem{Image(systemName:selectedTab==1 ? "heart.text.square.fill":"heart.text.square");Text("Health")}.tag(1)
            ProfileView().environmentObject(themeManager).tabItem{Image(systemName:selectedTab==2 ? "person.fill":"person");Text("Profile")}.tag(2)
        }
        .tint(themeManager.current == .dark ? .white : .black)
        .preferredColorScheme(themeManager.current.colorScheme)
    }
}
struct TodayView: View {
    @EnvironmentObject var themeManager:ThemeManager
    let nutritionPlan:NutritionPlan; let healthProfile:HealthProfile
    var body: some View { DashboardView().environmentObject(themeManager) }
}
